version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - "/home/chandra/Documents/cs:/code/data"
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    restart: always